### PR TITLE
Improvements to project files

### PR DESCRIPTION
**Pull request by bastianeicher**
This PR builds upon @shuebener's PR #182.

It adds automatic selection of target frameworks based on the MSBuild version. So it builds for `net20` only on platforms that support it.

It also adds an AppVeyor-based CI build. You can see an instance of it running against my fork [here](https://ci.appveyor.com/project/bastianeicher/ini-parser), already producing a NuGet package.

These two things combined make it so .NET Framework 2.0 can still be supported without making the project files unbuildable on platforms such as MacOS and Linux.

This PR also migrates the Example and Unit Test projects to the new project format and NUnit 3 (required for `dotnet test` support).

Note that there are some failing unit tests, but the appear to have already been red before the PR.

### CODE REVIEW

**Comment by rickyah** [comment]
I've been testing this on my local environments, both in mac and windows, and I had to modify your project files, partially to support a simple framework decision, but also to make the ini files used in the test to be copied to the output folder. However I'm having a failure when building on travis, that I just noticed you had too in the build that triggered for your PR:

https://travis-ci.org/rickyah/ini-parser/builds/497550546

All starts with this warning:
> /usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1899,5): warning : The referenced project '../INIFileParser/INIFileParser.csproj' does not exist. [/home/travis/build/rickyah/ini-parser/src/IniFileParser.Tests/INIFileParser.Tests.csproj]

And then the test project fails to build because it fails to locate references types defined in the IniFileParser, so it seem that the IniFileParser.Tests project cannot find a reference to the IniFileParser core project.
Any idea why this may be happening? 

For reference, this is my build, that fails for the exact same reason but with a different configuration:

https://travis-ci.org/rickyah/ini-parser/builds/522606684

**Comment by pulimento** [comment]
see https://github.com/rickyah/ini-parser/pull/188

**Comment by rickyah** [comment]
Oh My God. I stepped in the oldest error of all times: case sensitivity on file systems. Linux, specifically. That is what it was making my travis build to fail.

Well, now everything works both in I'm preparing a new PR with my branch, which is based on this one @bastianeicher

**Comment by rickyah** [comment]
Finally! Project builds both in mono and in dotnetcore!

https://travis-ci.org/rickyah/ini-parser/builds/535477869

Expect a v3.0 soon

**Pull request merged**
