### PR TITLE
Update to NUnit 3

### PR DESCRIPTION
**Pull request by Nothing4You**

### CODE REVIEW

**Comment by Nothing4You** [comment]
I'll fix the travis issue after lunch - probably just needs a different command in .travis.yml. Tests are passing locally.

**Comment by Nothing4You** [comment]
Tests are passing now, travis script needed some modification

**Comment by rickyah** [comment]
Thanks @Nothing4You 

However as I don't know if version 3 of nunit is compatible with .net2 I'll merge this PR into the v3.0 development branch.

**Comment by rickyah** [comment]
@Nothing4You have you tried running the test locally 
using runner from xamarin studio/visual studio for mac breaks a lot of tests, apparently the runner does not correctly uses the solution folder as root, so test that read/write files fail. Any input on this?

**Comment by rickyah** [comment]
Ok, fixed the problem, NUnit3 does not changes the working folder for the tests anymore https://github.com/nunit/nunit/issues/1072

**Comment by Nothing4You** [comment]
Regarding the directory changing, that's why I added the `cd` to the travis tests. Visual Studio 2017 didn't have any issues with that for me.
NUnit 3 should be compatible with .net 2.0, I don't see how it could otherwise be used as a dependency in a .net 2.0 project?
packages.config contains that aswell
```
+  <package id="NUnit" version="3.6.1" targetFramework="net20" />
+  <package id="NUnit.ConsoleRunner" version="3.6.1" targetFramework="net20" />
```

And https://www.nuget.org/packages/NUnit/ lists NET 2.0+ as supported platform.

**Comment by Nothing4You** [comment]
btw it'd be nice if this could get merged to master as this is one of the dependencies for #122 (which you should reopen). from what i have learned so far it should even be possible to keep .net 2.0 support while also supporting .net standard 1.6 with some hacks

**Pull request merged**
