### PR TITLE
Fixes #69: support concatenate duplicate keys.

### LINKED ISSUE #69: Unable to keep all duplicate keys
Thanks for this useful lib. I have an INI file with duplicate sections and a same key in every duplicate section. I would like to keep all these keys by concatenate all the values with a separator between them.

Here is an example of the INI file I would like to read.

```
[MySection]
File=a.txt
[MySection]
File=b.txt
[MySection]
File=c.txt
[MySection]
File=d.txt
```

I would like the lib to get the values in this way assuming that `; ` is used as the separator.

```
iniData["MySection"]["File"] = a.txt;b.txt;c.txt;d.txt
```

### PR DESCRIPTION
**Pull request by xtu**
I just fixed #69. Would you think it is OK to pull?

### CODE REVIEW

**Comment by rickyah** [comment]
The problem is that  `Configuration.OverrideDuplicateKeys` and  `Configuration.ConcatenateDuplicateKeys` are mutually exclusive: You can't set both configuration values to true because one of them will be ignored (ConcatenateDuplicateKeys will be ignored because it is the last in the if clause)

Also, it seems like a really extreme edge case. Why would you like to use multiple duplicate sections and name instead of just setting the File value directly?

```
[MySection]
File = a.txt;b.txt;c.txt;d.txt
```

**Comment by xtu** [comment]
Yes, these two settings are mutually exclusive, but I think we can document it somewhere to say they have a prioritized order. (`Configuration.OverrideDuplicateKeys` has a high priority than `Configuration.ConcatenateDuplicateKeys`).

I came across this problem when I tried to read a file which is provided by a third-party software. It stores data in this way thus I have to keep all these values in order to get the correct content.

**Comment by xtu** [comment]
I can encapsulate these settings into an enum and provide singular option for users. How about this solution?

**Comment by rickyah** [comment]
Been busy, I'll try to take a look at it this weekend. 
I'm thinking of creating a custom parser for this specific case

**Comment by rickyah** [comment]
@xtu i'm closing this PR because I've finally implemented a new parser that solves your problem. Please see PR #79

**Pull request closed without merging**
