### PR TITLE
Fix NullReferenceException when accessing not existing section

### PR DESCRIPTION
**Pull request by rickyah**
This PR is the same as #128 but removes the last commit

### CODE REVIEW

**Comment by Timer** [comment]
Is this landing any time soon? I could really use this.

**Comment by caverna** [comment]
For while, you may take my [fork](https://github.com/rickyah/ini-parser/pull/128/commits/37e19a00dd34b8cbf7148d4cacdb2437cc73537e)...
There you'll have a new setting: "AllowSectionsOnFly" (default: false)
This way, you won't have any exceptions.

**Comment by rickyah** [comment]
I'm trying to get some time to work on this, thing is I've recently became a father of a baby girls, so this first weeks is really hard to squeeze some free time 😆 

The thing is this change is actually a breaking change because it changes the behaviour of the library e.g. if somebody in his code is checking that a section is not null for some logic, this change would screw him up. I know is a fat chance, but I really want to bump up the major version of the library anyway

**Comment by caverna** [comment]
@rickyah , I let the default setting as FALSE, so it won't cause any compatibility issue with old code (old code still throwing exceptions until "AllowSectionsOnFly" be set as TRUE).

**Comment by rickyah** [comment]
@caverna I've merged your previous PR then

**Pull request closed without merging**
