### PR TITLE
Create internal interface ICloneable.

### PR DESCRIPTION
**Pull request by Nothing4You**
This is a required part to support .net standard 1.6 without changing internal implementations.

### CODE REVIEW

**Comment by rickyah** [comment]
And why is ICloneable not included in .net 1.6? I've actually used it because it has been there for ages

**Comment by Nothing4You** [comment]
Reasoning from one of the .net fx devs: http://stackoverflow.com/a/20386650

**Comment by rickyah** [comment]
I end up reading the page that answer directs to. As I said and as I'm happy to break compatibility for this version, I prefer dropping that interface and renaming the Clone() methods to something more semantic, like DeepCopy()

**Comment by rickyah** [comment]
Good news is I got apiport running again in the system and now seems to work ok on mac so I can generate the compatibility report

**Comment by Nothing4You** [comment]
Do you want this as a public interface?

**Pull request closed without merging**
