### PR TITLE
Update projects to new csproj format, VS2019. Target NetStandard and …

### PR DESCRIPTION
**Pull request by pulimento**
- Use new SDK project format
- Opens on Visual Studio 2019 (Windows and Mac) flawlessly
- Library project targets NetStandard 2.0
- Example and Test project targets NetCore 2.2
- Migrated to NUnit 3.8.x

Tested on Xamarin and UWP solutions. Feel free to ask if you need some changes on this PR :)

### CODE REVIEW

**Comment by pulimento** [comment]
got bored of travis, build just works fine locally (tried on mac and windows)

**Comment by pulimento** [comment]
At least! TravisCI working, on a project fully compatible with NetStandard / NetCore 🎉🎉
If you were looking for a 3.0 release, here it is! 😃

**Comment by rickyah** [comment]
First of all, "mil gracias" for your PR Javi 😉 

The problem with your PR is that it fully embraces the dotnet core ecosystem, removing support for older tech. There is an open PR https://github.com/rickyah/ini-parser/pull/185 that tries to maintain compatibility with older projects. However, I've been unable to make it build on travis, maybe you can provide some insight? 

Here is the development branch:
https://github.com/rickyah/ini-parser/commits/bastianeicher-development
You'll notice that it contains changes similar to yours in this PR

And here is the travis log:
https://travis-ci.org/rickyah/ini-parser/builds/522749725

**Comment by pulimento** [comment]
hey! glad you have the work done (I saw your comment in the another PR). Perhaps you can pick manually best from both PRs. Then, feel free to close this one.

**Comment by rickyah** [comment]
I'm going to take a look at your changes and compare with mine and see if I can use some commits ;)

**Comment by miya898** [comment]
Hi, happy to know that ini-parser will support .netcore. Could I ask when the new package will be released with fix#188?

**Pull request closed without merging**
