### PR TITLE
Allow setting the newline string used when writing a file

### PR DESCRIPTION
**Pull request by rickyah**
As requested in issue #108 by @sergiorykov the poor soul (:wink:) that needs to create files with unix endlines on windows

### CODE REVIEW

**Comment by sergiorykov** [comment]
Yep!

**Comment by sergiorykov** [comment]
Maintenance release will be pretty useful :).

**Comment by rickyah** [comment]
I'll create a new version when I arrive home @sergiorykov

**Comment by rickyah** [comment]
You got it @sergiorykov 
https://www.nuget.org/packages/ini-parser/2.3.0

**Pull request merged**
